version: '3.7'
services:
    app:
        build:
            args:
                user: ${USER}
                uid: 1000
            context: ./
            dockerfile: ./docker/php/Dockerfile
        image: quest-csv
        container_name: quest-csv-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - quest-csv
    db:
        image: mysql:5.7
        container_name: quest-csv-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: quest-csv
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql/db.sql:/docker-entrypoint-initdb.d/db.sql"
            - ./docker/mysql:/docker-entrypoint-initdb.d
        networks:
            - quest-csv
networks:
    questcsv:
        driver: bridge
