#!/usr/bin/env php
<?php

declare(strict_types=1);

use Quest\Commands\BannerCommand;

if (php_sapi_name() != 'cli') {
    die("<h1>Execução permitida apenas em modo CLI</h1>");
}

require_once 'bootstrap.php';

if (isset($argv[1]) && in_array($argv[1], ['--help', '-h'])) {
    BannerCommand::help();
    return;
}

BannerCommand::init();

if (isset($argv[1]) && in_array($argv[1], ['--seed', '-s'])) {

    $app->seed();
}
